apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    file_storage_access_mode: ReadWriteOnce
    file_storage_size: 100Gi
    gunicorn_api_workers: 1
    gunicorn_content_workers: 1
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
  no_log: true
  redis_mode: standalone
  route_tls_termination_mechanism: Edge
