apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-rwx
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0006e42e83f712007 # your EFS ID
  directoryPerms: "700"
mountOptions:
  - tls
reclaimPolicy: Retain
volumeBindingMode: Immediate
